### ISSUE TITLE
Synchronisation with GitHub repositories

### ISSUE THREAD

**Issue by bluelhf** [PaperMC/Hangar#235] opened 2020-11-14 08:49 UTC
### Suggestion
**Currently, on platforms like SpigotMC, making new releases or making changes to the read-me of a project takes a lot more effort than it should.**

It'd be nice to see something in Hangar to automatically sync a project page with a corresponding repository - This way, project developers would only have to update the GitHub repository of the project and the changes would be automatically reflected on the Hangar page.

![Depiction of the settings box for github integration and how it would work](https://user-images.githubusercontent.com/52505120/99143543-ebd42280-2666-11eb-9cf8-26bcf4671c91.png)

**Comment by notOM3GA** [comment] 2020-11-14 11:47
webhooks could also be used for this kind of thing

**Comment by KennyTV** [comment] 2020-11-14 11:50
Duplicate of #39

**Closed by KennyTV** 2020-11-14 11:50 UTC

**Comment by Machine-Maker** [comment] 2020-11-14 16:48
I *think* the only integration with various repo-hosting sites will be an api to deploy new versions. And this might not even be platform-specific. You can probably write a github action that uses the already-existing deploy api endpoint to release new versions when they are created on github. That way, hangar doesn't have to include any github-specific code, that wouldnt work for gitlab, or bitbucket, or any other repository site.

**Comment by Chew** [comment] 2020-11-14 19:15
Honestly a lovely diagram lol
