### ISSUE TITLE
Suggest(Feat): Github Releases integration. 

### ISSUE THREAD

**Issue by steviebeenz** [PaperMC/Hangar#165] opened 2020-10-04 06:39 UTC
Allow resources to be auto updated using github releases, and copy version + description from the release.

This would need some limitations (1 file releases only etc)

**Comment by Machine-Maker** [comment] 2020-10-04 06:40
You mean with gh webhooks?

**Comment by steviebeenz** [comment] 2020-10-04 06:47
> You mean with gh webhooks?

That could be a way to implement it...

**Comment by KennyTV** [comment] 2020-10-04 06:49
Duplicate of #39, even if it's just a button on version creation

**Closed by KennyTV** 2020-10-04 06:49 UTC
