### ISSUE TITLE
Avatar in project members list is not displayed correctly

### ISSUE THREAD

**Issue by PeachesMLG** [PaperMC/Hangar#292] opened 2020-12-29 20:17 UTC
https://hangar.minidigger.me/Peaches_MLG/IridiumSkyblock
https://imgur.com/HjMgKTJ.png

**Comment by KennyTV** [comment] 2020-12-30 21:54
That's your avatar not loading and just displaying its title (being your name).

**Comment by MiniDigger** [comment] 2020-12-30 21:55
Which then makes this a duplicate of #290

**Closed by MiniDigger** 2020-12-30 21:55 UTC
